// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"ecommerce_go/internal/controller"
	"ecommerce_go/internal/repo"
	"ecommerce_go/internal/service"
)

// Injectors from user.wire.go:

func InitUserRouterHanlder() (controller.IUserController, error) {
	iUserRepo := repo.NewUserRepo()
	iUserAuthRepo := repo.NewUserAuthRepo()
	iUserService := service.NewUserService(iUserRepo, iUserAuthRepo)
	iUserController := controller.NewUserController(iUserService)
	return iUserController, nil
}
