// // Code generated by Wire. DO NOT EDIT.

// //go:generate go run -mod=mod github.com/google/wire/cmd/wire
// //go:build !wireinject
// // +build !wireinject

package wire

// import (
// 	"ecommerce_go/internal/controller"
// 	"ecommerce_go/internal/repo"
// 	"ecommerce_go/internal/service/implement"
// )

// // Injectors from user.wire.go:

// func InitUserRouterHanlder() (controller.IUserController, error) {
// 	iUserRepo := repo.NewUserRepo()
// 	iUserAuthRepo := repo.NewUserAuthRepo()
// 	iUserLogin := service.NewUserLogin(iUserRepo, iUserAuthRepo)
// 	iUserController := controller.NewUserController(iUserLogin)
// 	return iUserController, nil
// }
