server:
  port: 8081
  model: "dev"
mysql:
  username: root
  password: cmmtpnx1
  host: 127.0.0.1 #mysql_container
  port: 3307
  dbname: shopdevgo
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifeTime: 3600
security:
  key: tuulee
log:
  logLevel: debug
  fileLogName: "./storage/logs/log-%s.txt"
  maxSize:    500
  maxBackups: 213
  maxAge:     20
  compress:   true
redis:
  username: tulehd03
  password: Cmmtpnx1!
  addr: "redis-17965.c295.ap-southeast-1-1.ec2.redns.redis-cloud.com:17965"
  db: 0
  poolSize: 10
email:
  SMTPUsername: ERP.nhacungcap1@gmail.com
  SMTPPassword: mhzoeojbvpimgjvj
