@baseUrl=http://localhost:8889

### User Registration
POST {{baseUrl}}/action/stock
Content-type: application/json

{
    "Email": "tulehd03@gmail.com",
    "Password": "TEST_USER"
}

### 
GET {{baseUrl}}/users/login